### ISSUE TITLE
PineJS tradingview charting library

### ISSUE THREAD

**Issue by lezwright** [pinecoders/pinecoders.github.io#62]
Hi, would you be able to let me know if the PineJS used in tradingview charting library custom studies same as Pine codes in Tradingview platform? Would possibly know if there is any handbook available for that?

**Comment by LucFF** [comment]
Sorry but I don't know those products. You can register here or contact support: https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts
