### ISSUE TITLE
Pinescript dictionnary integration

### ISSUE THREAD

**Issue by RomainPhil** [pinecoders/pinecoders.github.io#65]
Hi,

I'v discover the pine script recently and the maintainability of some of my script start to become really complicated du to the absence of the object working like a dictionnary  [python example](https://www.w3schools.com/python/python_dictionaries.asp) and the fact the array tipe can't  store a string https://www.tradingview.com/pine-script-docs/en/v4/language/Type_system.html#array

the size of a script attain more than 200 line with many If impricate and for each etf add to this the size grow up exponentially
which wouldn't be the case with  the two programatic upgrade: dictionnary and the possibility for array to store string and the a dictionnary object

**Comment by popopame** [comment]
+ 1 
Writing understandable and maintainable Script is borderline impossible without dictionary and proper loop.

This would be a excellent addition to pine script.

**Comment by megasyl** [comment]
Hi,
I support this suggestion. I'm happy to read a 'yet', any news about it ? :D

**Comment by LucFF** [comment]
Specs for maps are done but they are not in the pipeline yet. 2022 should see 2d arrays first, and then maps, perhaps. No promises.
